baseurl = "/"
title = "Fish Sec ::: ><)))]°>"
languageCode = "en-us"
paginate = "3" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Julien"
  bio = "Julien is an avid learner, with a few years of experience in the fields of application security and penetration testing. Aside from computers, he is enthralled by the joys of rock-climbing and dancing."
  avatar = "img/avatar.png"

[Params]
  subtitle = "All things security" # Subtitle of your site
  description = "Description" # Description of your site
  opengraph = false
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  post_navigation = false
  post_meta = ["date", "categories"] # Order of post meta information
  customCSS = ["css/custom.css"] # Include custom CSS files
  # Global variable for highlighted color $highlightColor in custom.css
  highlightColor = "#d5d5d5"
  
[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
